services:

  mysql:
    image: mysql:8.0
    container_name: hospital-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospitaldb
    expose:
      - "3306"
    networks:
      - hospital-net

  app:
    image: ${DOCKER_USERNAME}/hospital-system:latest
    container_name: hospital-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hospitaldb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - hospital-net

networks:
  hospital-net: